<?xml version="1.0"?>
<!--

  Copyright (c) 2011-2014, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ant_description)/urdf/deg_to_rad.xacro" />
  <xacro:include filename="$(find ant_description)/urdf/base/base.transmission.xacro" />

  <xacro:include filename="$(find ant_description)/urdf/sensors/range.urdf.xacro" />
  <xacro:include filename="$(find ant_description)/urdf/sensors/hokuyo_urg_04lx_ug01_laser.urdf.xacro" />
  <xacro:include filename="$(find ant_description)/urdf/sensors/imu.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/sensors/bumper.urdf.xacro" />

  <!--wheel characteristics-->
  <property name="wheel_separation" value="0.42"/>
  <property name="wheel_radius"     value="0.09931"/>
  <property name="wheel_width"      value="0.03737"/>
  <property name="wheel_torque"     value="50.0"/>
  <property name="wheel_velocity"   value="1.0"/>

  <!--caster characteristics-->
  <property name="dist_between_casters" value="0.300"/>
  <property name="caster_radius"        value="0.025"/>
  <property name="caster_width"         value="0.0164"/>
  <property name="caster_trailing_dist" value="0.038"/>

  <xacro:macro name="ant_wheel" params="side reflect" parent="base_link">

    <!--************************-->
    <!--        WHEELS          -->
    <!--************************-->
    <link name="wheel_${side}_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1.0" />
        <inertia ixx="1"  ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
        <!--<origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="3.5" />
        <inertia ixx="0.00156"  ixy="0"  ixz="0" iyy="0.00156" iyz="0" izz="0.0273" />-->
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <material name="DarkGrey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
    </link>

  <!-- contact model for wheel surface -->
   <gazebo reference="wheel_${side}_link">
     <kp>100000000.0</kp>
     <kd>10000.0</kd>
     <mu1>1.0</mu1>
     <mu2>1.0</mu2>
     <minDepth>0.00</minDepth>
   </gazebo>

    <joint name="wheel_${side}_joint" type="continuous">
      <parent link="base_link" />
      <child link="wheel_${side}_link" />
      <origin xyz="0 ${-wheel_separation / 2 * reflect} ${wheel_radius}" rpy="${-90.0 * deg_to_rad} 0 0" />
      <axis xyz="0 0 1" />
      <limit effort="${wheel_torque}" velocity="${wheel_velocity / wheel_radius}"/>
    </joint>

    <!-- extensions -->
    <xacro:ant_wheel_transmission side="${side}" />

  </xacro:macro>

  <xacro:macro name="ant_caster" params="side reflect">
    <!--************************-->
    <!--        CASTERS         -->
    <!--************************-->

    <link name="caster_${side}_1_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                  iyy="0.015218160428" iyz="-0.000004273467"
                  izz="0.011763977943" />
      </inertial>
      <visual>
        <origin xyz="${0.5 * caster_radius - caster_trailing_dist} 0 ${0.5 * caster_radius}" rpy="0 0 0" />
        <geometry>
          <box size="${caster_radius} ${1.2 * caster_width} ${caster_radius}"/>
        </geometry>
        <material name="DarkGrey" />
      </visual>
      <collision>
        <origin xyz="${0.5 * caster_radius - caster_trailing_dist} 0 ${0.5 * caster_radius}" rpy="0 0 0" />
        <geometry>
          <box size="${caster_radius} ${1.2 * caster_width} ${caster_radius}"/>
        </geometry>
      </collision>
    </link>

    <link name="caster_${side}_2_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.4" />
        <inertia  ixx="0.00044" ixy="0" ixz="0" iyy="0.00044" iyz="0" izz="0.00078" />
        </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${caster_radius}" length="${caster_width}"/>
        </geometry>
        <material name="DarkGrey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${caster_radius}" length="${caster_width}"/>
        </geometry>
      </collision>
    </link>

   <!-- contact model for caster wheel surface -->
   <gazebo reference="caster_${side}_2_link">
     <kp>100000000.0</kp>
     <kd>10000.0</kd>
     <mu1>1.0</mu1>
     <mu2>1.0</mu2>
     <minDepth>0.00</minDepth>
   </gazebo>

    <joint name="caster_${side}_1_joint" type="continuous">
      <parent link="base_link" />
      <child link="caster_${side}_1_link" />
      <origin xyz="-0.3805 ${-dist_between_casters / 2 * reflect} ${caster_radius}" rpy="0 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <joint name="caster_${side}_2_joint" type="continuous">
      <parent link="caster_${side}_1_link" />
      <child link="caster_${side}_2_link" />
      <origin xyz="${-caster_trailing_dist} 0 0" rpy="${-90.0 * deg_to_rad} 0 0" />
      <axis xyz="0 0 1" />
    </joint>
  </xacro:macro>

  <!-- simplified box collision geometry for the laser -->
  <property name="base_laser_x" value="0.0468" />
  <property name="base_laser_y" value="0.0" />
  <property name="base_laser_z" value="0.081" />

  <!-- base_link x-axis offset -->
  <property name="base_link_offset_x" value="0.0"/>

  <xacro:macro name="ant_base" params="name">

    <!--************************-->
    <!--        BASE            -->
    <!--************************-->

    <link name="${name}_link">
      <inertial>
        <origin xyz="0.0 0.0 0.24721" rpy="0 0 0" /> <!-- assuming d=0.6, w=0.5, h=0.4 -->
        <mass value="63.58850" />
        <inertia ixx="3.42"  ixy="0"  ixz="0" iyy="4.33" iyz="0" izz="5.08" /> <!-- assuming d=0.6, w=0.5, h=0.4 -->
      </inertial>
      <visual>
        <origin xyz="${base_link_offset_x} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://ant_description/meshes/base/base.dae" />
        </geometry>
        <material name="LightGrey" />
      </visual>
      <collision>
        <origin xyz="${base_link_offset_x} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://ant_description/meshes/base/base_collision.stl" />
        </geometry>
        <material name="LightGrey" />
      </collision>
    </link>

    <!-- base_footprint fictitious link(frame). It coincides with base_link in our case. Provided for convenience when
    using the navigation stack -->
    <link name="${name}_footprint">
      <visual>
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
        <material name="White" />
      </visual>
      <collision>
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>

    <joint name="${name}_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <child link="${name}_link" />
      <parent link="${name}_footprint"/>
    </joint>

    <link name="${name}_center">
      <inertial>
        <mass value="1.0" />
        <origin xyz="-0.0 0 0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                 iyy="0.01" iyz="0.0" izz="0.01" />
      </inertial>
      <visual>
        <origin xyz="-0.0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
        <material name="White" />
      </visual>
      <collision>
        <origin xyz="-0.0 0 0.2" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>

    <joint name="${name}_center_joint" type="fixed">
      <origin xyz="${-0.195 + base_link_offset_x} 0 0" rpy="0 0 0" />
      <child link="${name}_center" />
      <parent link="${name}_link"/>
    </joint>

    <!-- laser -->
    <xacro:hokuyo_urg_04lx_ug01_laser name="${name}_laser" parent="${name}" ros_topic="scan" update_rate="10" min_angle="${-120 * deg_to_rad}" max_angle="${120 * deg_to_rad}" >
      <origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="0 0 0" />
    </xacro:hokuyo_urg_04lx_ug01_laser>

    <!-- sonar -->
    <xacro:range_ant name="${name}_sonar_02" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="${0.17131 + base_link_offset_x} 0.0 0.280" rpy="0.0 0.0 0.0" />
    </xacro:range_ant>

    <!-- sonar -->
    <xacro:range_ant name="${name}_sonar_03" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="${0.16919 + base_link_offset_x} 0.14919 0.280" rpy="0.0 0.0 0.349" />
    </xacro:range_ant>

    <!-- sonar -->
    <xacro:range_ant name="${name}_sonar_01" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="${0.16919 + base_link_offset_x} -0.14919 0.280" rpy="0.0 0.0 -0.349" />
    </xacro:range_ant>

    <!-- bumper front right -->
    <xacro:bumper_ant name="${name}_bumper_01" parent="${name}" ros_topic="bumper_base" update_rate="25" >
      <origin xyz="${0.225 + base_link_offset_x} -0.15 0.20" rpy="0 0 ${-15.0 * deg_to_rad}" />
    </xacro:bumper_ant>

    <!-- bumper front left -->
    <xacro:bumper_ant name="${name}_bumper_02" parent="${name}" ros_topic="bumper_base" update_rate="25" >
      <origin xyz="${0.225 + base_link_offset_x} 0.15 0.20" rpy="0 0 ${15.0 * deg_to_rad}" />
    </xacro:bumper_ant>

    <!-- imu -->
    <xacro:ant_imu name="base_inclinometer" parent="${name}_link" update_rate="100.0">
      <origin xyz="-0.02977 -0.1497 0.164" rpy="0 ${180 * deg_to_rad} 0"/>
    </xacro:ant_imu>

    <!-- wheels -->
    <xacro:ant_wheel side="right" reflect=" 1.0"/>
    <xacro:ant_wheel side="left"  reflect="-1.0"/>

    <!-- casters -->
    <xacro:ant_caster side="right" reflect=" 1.0"/>
    <xacro:ant_caster side="left"  reflect="-1.0"/>

  </xacro:macro>

</robot>
