<?xml version="1.0"?>
<!--

  Copyright (c) 2011-2014, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ant_description)/urdf/deg_to_rad.xacro" />

  <xacro:include filename="$(find ant_description)/urdf/wheels/wheel.urdf.xacro" />
  <xacro:include filename="$(find ant_description)/urdf/wheels/caster.urdf.xacro" />

  <xacro:include filename="$(find ant_description)/urdf/sensors/range.urdf.xacro" />
  <xacro:include filename="$(find ant_description)/urdf/sensors/hokuyo_urg_04lx_ug01_laser.urdf.xacro" />
  <xacro:include filename="$(find ant_description)/urdf/sensors/imu.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/sensors/bumper.urdf.xacro" />

  <!-- Wheel characteristics -->
  <property name="wheel_separation" value="0.42"/>
  <property name="wheel_radius"     value="0.09931"/>
  <property name="wheel_width"      value="0.03737"/>
  <property name="wheel_torque"     value="50.0"/>
  <property name="wheel_velocity"   value="1.0"/>

  <!-- Caster wheel characteristics -->
  <property name="caster_separation" value="0.300"/>
  <property name="caster_radius"     value="0.025"/>
  <property name="caster_width"      value="0.0164"/>
  <property name="caster_trailing"   value="0.138"/>

  <!-- base_link x-axis offset -->
  <property name="base_link_offset_x" value="0.0"/>

  <property name="base_radius" value="${(wheel_separation - wheel_width)/2 - 0.01}"/>
  <property name="base_length" value="0.04"/>
  <property name="base_link_offset_z" value="${base_length + 0.01}"/>

  <!-- simplified box collision geometry for the laser -->
  <property name="base_laser_x" value="0.15"/>
  <property name="base_laser_y" value="0.0"/>
  <property name="base_laser_z" value="0.081"/>

  <xacro:macro name="ant_base" params="name">

    <!--************************-->
    <!--        BASE            -->
    <!--************************-->

    <link name="${name}_link">
      <inertial>
        <origin xyz="0.0 0.0 0.24721" rpy="0 0 0" /> <!-- assuming d=0.6, w=0.5, h=0.4 -->
        <mass value="63.58850" />
        <inertia ixx="3.42"  ixy="0"  ixz="0" iyy="4.33" iyz="0" izz="5.08" /> <!-- assuming d=0.6, w=0.5, h=0.4 -->
      </inertial>
      <visual>
        <origin xyz="${base_link_offset_x} 0 ${base_link_offset_z}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${base_radius}" length="${base_length}"/>
          <!--mesh filename="package://ant_description/meshes/base/base.dae" /-->
        </geometry>
        <material name="LightGrey" />
      </visual>
      <collision>
        <origin xyz="${base_link_offset_x} 0 ${base_link_offset_z}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${base_radius}" length="${base_length}"/>
          <!--mesh filename="package://ant_description/meshes/base/base_collision.stl" /-->
        </geometry>
        <material name="LightGrey" />
      </collision>
    </link>

    <!-- base_footprint fictitious link(frame). It coincides with base_link in our case. Provided for convenience when
    using the navigation stack -->
    <link name="${name}_footprint">
      <collision>
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>

    <joint name="${name}_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <child link="${name}_link" />
      <parent link="${name}_footprint"/>
    </joint>

    <!-- Laser -->
    <xacro:hokuyo_urg_04lx_ug01_laser name="${name}_laser" parent="${name}" ros_topic="scan" update_rate="10" min_angle="${-120 * deg_to_rad}" max_angle="${120 * deg_to_rad}" >
      <origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="0 0 0" />
    </xacro:hokuyo_urg_04lx_ug01_laser>

    <!-- Sonar -->
    <xacro:range_ant name="${name}_sonar_02" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="${0.17131 + base_link_offset_x} 0.0 0.280" rpy="0.0 0.0 0.0" />
    </xacro:range_ant>

    <!-- Sonar -->
    <xacro:range_ant name="${name}_sonar_03" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="${0.16919 + base_link_offset_x} 0.14919 0.280" rpy="0.0 0.0 0.349" />
    </xacro:range_ant>

    <!-- Sonar -->
    <xacro:range_ant name="${name}_sonar_01" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="${0.16919 + base_link_offset_x} -0.14919 0.280" rpy="0.0 0.0 -0.349" />
    </xacro:range_ant>

    <!-- Bumper front right -->
    <xacro:bumper_ant name="${name}_bumper_01" parent="${name}" ros_topic="bumper_base" update_rate="25" >
      <origin xyz="${0.225 + base_link_offset_x} -0.15 0.20" rpy="0 0 ${-15.0 * deg_to_rad}" />
    </xacro:bumper_ant>

    <!-- Bumper front left -->
    <xacro:bumper_ant name="${name}_bumper_02" parent="${name}" ros_topic="bumper_base" update_rate="25" >
      <origin xyz="${0.225 + base_link_offset_x} 0.15 0.20" rpy="0 0 ${15.0 * deg_to_rad}" />
    </xacro:bumper_ant>

    <!-- IMU -->
    <xacro:ant_imu name="base_inclinometer" parent="${name}_link" update_rate="100.0">
      <origin xyz="-0.02977 -0.1497 0.164" rpy="0 ${180 * deg_to_rad} 0"/>
    </xacro:ant_imu>

    <!-- Wheels -->
    <xacro:wheel_ant side="right" reflect=" 1.0" radius="${wheel_radius}" width="${wheel_width}" torque="${wheel_torque}" velocity="${wheel_velocity}" separation="${wheel_separation}" parent="${name}"/>
    <xacro:wheel_ant side="left"  reflect="-1.0" radius="${wheel_radius}" width="${wheel_width}" torque="${wheel_torque}" velocity="${wheel_velocity}" separation="${wheel_separation}" parent="${name}"/>

    <!-- Casters wheels -->
    <xacro:caster_ant side="right" reflect=" 1.0" radius="${caster_radius}" width="${caster_width}" separation="${caster_separation}" trailing="${caster_trailing}" parent="${name}"/>
    <xacro:caster_ant side="left"  reflect="-1.0" radius="${caster_radius}" width="${caster_width}" separation="${caster_separation}" trailing="${caster_trailing}" parent="${name}"/>

  </xacro:macro>

</robot>
