<?xml version="1.0"?>

<!--
  Copyright (c) 2011, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ant_description)/urdf/wheels/caster.gazebo.xacro"/>

  <xacro:macro name="caster_ant" params="side reflect radius width separation trailing parent">
    <link name="caster_${side}_1_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                  iyy="0.015218160428" iyz="-0.000004273467"
                  izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="${0.5 * radius - trailing} 0 ${0.5 * radius}" rpy="0 0 0"/>
        <geometry>
          <box size="${radius} ${1.2 * width} ${radius}"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <origin xyz="${0.5 * radius - trailing} 0 ${0.5 * radius}" rpy="0 0 0"/>
        <geometry>
          <box size="${radius} ${1.2 * width} ${radius}"/>
        </geometry>
      </collision>
    </link>

    <link name="caster_${side}_2_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.4"/>
        <inertia  ixx="0.00044" ixy="0" ixz="0" iyy="0.00044" iyz="0" izz="0.00078"/>
        </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="caster_${side}_1_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="caster_${side}_1_link"/>
      <origin xyz="-0.3805 ${-separation / 2 * reflect} ${radius}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="caster_${side}_2_joint" type="continuous">
      <parent link="caster_${side}_1_link"/>
      <child link="caster_${side}_2_link"/>
      <origin xyz="${-trailing} 0 0" rpy="${-90.0 * deg_to_rad} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <!-- gazebo extensions -->
    <xacro:caster_ant_gazebo side="${side}"/>
  </xacro:macro>
</robot>
