speed_limit:
  reporters:
    ant_web:
      type: reem_topic
  limiters:
    base_laser:
      type: laser
      topic: scan
      disabled: false
      obstacle_max_dist: 1.5
      stop_dist: 0.0   # no padding around the footprint
      #stop_dist: 0.3    # when not using the footprint
      speed_factor: 0.5
      fixed: true

    rgbd_laser:
      type: laser
      topic: rgbd_scan
      disabled: true
      obstacle_max_dist: 1.5
      stop_dist: 0.3   # padding around the footprint, because of the RGBD sensor blanking
      #stop_dist: 0.6    # when not using the footprint
      speed_factor: 0.5
      fixed: true

#    base_sonars:
#      type: range
#      topic: sonar_base
#      disabled: true
#      obstacle_max_dist: 0.6
#      stop_dist: 0.1
#      speed_factor: 0.3
#      blacklist: []
#      whitelist: []
#      fixed: true

#    base_irs:
#      type: range
#      topic: ir_base
#      disabled: true
#      obstacle_max_dist: 1.0
#      stop_dist: 0.2
#      speed_factor: 0.5
#      blacklist: []
#      whitelist: []
#      fixed: true

#    base_bumpers:
#      type: bumper
#      topic: bumper_base
#      disabled: true
#      obstacle_max_dist: 1.0
#      stop_dist: 1.0
#      speed_factor: 1.0
#      blacklist: []
#      whitelist: []
#      fixed: true
